---
language: "python"
python: "2.7"

env:
  - SITE_SYSTEM_AND_INVENTORY="tests/test_system.yml -i tests/inventory"
  - SITE_HOME_AND_INVENTORY="tests/test_home.yml -i tests/inventory"

before_install:
  - "rvm get head ; __rvm_unload ; ~/.rvm/bin/rvm --trace --force implode"
  - "rm -rf ~/.rvm"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook $SITE_SYSTEM_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_SYSTEM_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_SYSTEM_AND_INVENTORY --connection=local
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    ruby -v
    | grep -q 'ruby'
    && (echo 'Version test: pass' && exit 0)
    || (echo 'Version test: fail' && exit 1)
  - "rvm get head ; __rvm_unload ; ~/.rvm/bin/rvm --trace --force implode"
  - "rm -rf ~/.rvm"
  - "ansible-playbook $SITE_HOME_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_HOME_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_HOME_AND_INVENTORY --connection=local
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    ruby -v
    | grep -q 'ruby'
    && (echo 'Version test: pass' && exit 0)
    || (echo 'Version test: fail' && exit 1)